spring:
  application:
    name: verification_service

tesseract:
  data:
    path: "src/main/resources/tessdata"
    language: "eng"
  jna:
    path: "/opt/homebrew/lib" # Apple M series specific

server:
  port: 6400